### ISSUE TITLE
Just shuts down?

### ISSUE THREAD

**Issue by 57194** [bfren/docker-ftps#139]
```yaml
  # FTPS #
  ftps:
    image: "ghcr.io/bfren/ftps:latest"
    container_name: "ftps"
    restart: "unless-stopped"
    ports: [ "172.20.69.3:990:990", "172.20.69.3:18700-18710:18700-18710" ]
    volumes:
      - "/mnt/media/public:/files:ro"
      - "/path/to/my.pem:/ssl/vsftpd.pem:ro"
    env_file: "./envs/ftps.env"
  # FTPS #
```

```env
BF_FTPS_EXTERNAL_URI=example.com
BF_FTPS_SSL_BITS=4096
BF_FTPS_VSFTPD_USER=user
BF_FTPS_VSFTPD_PASS=password
BF_FTPS_VSFTPD_UID=1000
BF_FTPS_LFTP_VERIFY_CERT=yes
```

```log
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init: starting
[bf] 2024-09-05 02:00:23 | init: Initialising container.
[bf] 2024-09-05 02:00:23 | init/execute: 00-welcome.nu.
#=====================================================================================================================#

 _      __                  _    __ _
| |__  / _|_ __ ___ _ __   | |  / _| |_ _ __  ___
| '_ \| |_| '__/ _ \ '_ \  | | | |_| __| '_ \/ __|
| |_) |  _| | |  __/ | | | | | |  _| |_| |_) \__ \
|_.__/|_| |_|  \___|_| |_| | | |_|  \__| .__/|___/
                           |_|         |_|


bfren/ftps:4.2.15 [alpine:3.20.2] [vsftpd:3.0.5-r2]
Built on Fri, 30 Aug 2024 15:54:12 +0100 (5 days ago)


https://github.com/bfren/docker-ftps

#=====================================================================================================================#
[bf] 2024-09-05 02:00:24 | init/execute: 01-env.nu.
[bf] 2024-09-05 02:00:24 | init/execute: 02-ch.nu.
[bf] 2024-09-05 02:00:24 | 02-ch.nu: Applying /etc/bf/ch.d/00-bf. (ch/apply_file)
[bf] 2024-09-05 02:00:24 | 02-ch.nu: Applying /etc/bf/ch.d/01-cron. (ch/apply_file)
[bf] 2024-09-05 02:00:24 | init/execute: 03-tz.nu.
[bf] 2024-09-05 02:00:24 | init/execute: 04-cron.nu.
/etc/crontabs/root
[bf] 2024-09-05 02:00:24 | init/execute: 10-env.nu.
[bf] 2024-09-05 02:00:24 | init/execute: 11-user.nu.
[bf] 2024-09-05 02:00:24 | 11-user.nu: Creating user asak.
[bf] 2024-09-05 02:00:24 | 11-user.nu: Ensuring user asak owns /files.
[bf] 2024-09-05 02:00:29 | init/execute: 12-vsftpd-log.nu.
[bf] 2024-09-05 02:00:30 | 12-vsftpd-log.nu: Creating log file.
[bf] 2024-09-05 02:00:30 | init/execute: 13-vsftpd-ssl.nu.
[bf] 2024-09-05 02:00:30 | 13-vsftpd-ssl.nu: SSL certificate already exists.
[bf] 2024-09-05 02:00:30 | init/execute: 14-vsftpd-conf.nu.
[bf] 2024-09-05 02:00:30 | 14-vsftpd-conf.nu: Generating vsftpd configuration.
/etc/vsftpd/vsftpd.conf
[bf] 2024-09-05 02:00:30 | init/execute: 15-lftp-conf.nu.
[bf] 2024-09-05 02:00:30 | 15-lftp-conf.nu: Generating lftp configuration.
/etc/lftp.conf
[bf] 2024-09-05 02:00:30 | init/up: Initialisation complete.
s6-rc: info: service init successfully started
s6-rc: info: service vsftpd: starting
s6-rc: info: service cron: starting
s6-rc: info: service cron successfully started
s6-rc: info: service vsftpd successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[bf] 2024-09-05 02:00:30 | vsftpd/run: Starting vsftpd.
[bf] 2024-09-05 02:00:30 | cron/run: Starting cron in foreground mode.
[bf] 2024-09-05 02:00:30 | bf-cont-terminate: Terminating container, goodbye. (cont/terminate)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service vsftpd: stopping
s6-rc: info: service cron: stopping
s6-rc: info: service vsftpd successfully stopped
[bf] 2024-09-05 02:00:31 | bf-cont-terminate: Terminating container, goodbye. (cont/terminate)
s6-rc: info: service cron successfully stopped
s6-rc: info: service init: stopping
s6-rc: info: service init successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by bfren** [comment]
Can you add BF_DEBUG=1 as an environment variable and try again, in case there is any further output that might help with troubleshooting?

**Comment by bfren** [comment]
Hmmm I'm at a bit of a loss there I'm afraid - it looks to me like vsftpd is bugging out for some reason.  I've been playing around this morning with some vsftpd logging options but can't get them to work.  I'll keep playing to see if I can get it to emit anything useful!

This is my compose file that I use on one of my servers.  Differences I can see are in port mapping and I explicitly specify a network - but I'm not convinced either of those will make a difference!

```yaml
services:
  ftps:
    image: bfren/ftps:latest
    container_name: ftps
    restart: unless-stopped
    ports:
      - "0.0.0.0:21:21"
      - "0.0.0.0:990:990"
      - "0.0.0.0:18700-18710:18700-18710"
    environment:
      - BF_FTPS_EXTERNAL_URI=xxx
      - BF_FTPS_VSFTPD_USER=xxx
      - BF_FTPS_VSFTPD_PASS=xxx
    volumes:
      - ./v/files:/files
      - /data/proxy/v/ssl/certs/xxx/xxx.pem:/ssl/vsftpd.pem:ro
    networks:
      - ftps

networks:
  ftps:
    driver: bridge
    name: ftps
```
