### ISSUE TITLE
passive ports

### ISSUE THREAD

**Issue by pc0124** [bfren/docker-ftps#148]
could you make the `pasv_min_port` and `pasv_max_port` values configurable? assigning values other than those defined in  `vsftpd.conf.esh` `"18700-18710:18700-18710"` leads to error. i still can't make two containers running at the same time maybe because of this, trying to narrow it down.

```
Response:	227 Entering Passive Mode (192,168,1,111,73,18).
Command:	LIST
Error:	The data connection could not be established: ECONNREFUSED - Connection refused by server
```

**Comment by bfren** [comment]
Hi @pc0124, thanks for using the image!

The way to do this would be through port mapping rather than changing the ports in the container itself, for example:

```Dockerfile
services:
  ftp_0:
    ...
    ports:
      - "0.0.0.0:10000-10010:18700-18710"
  ftp_1:
    ...
    ports:
      - "0.0.0.0:20000-20010:18700-18710"
```

The trick is to ensure the source port range (in this example 10000-10010 and 20000-20010) is the same length as the destination range (18700-18710).

**However** the main issue isn't the passive ports it's the starting ports: 21 and 990.  I have never managed to change those successfully - and you can't map them to two separate containers.  So the above configuration would only work if you only ran one of the above containers at a time, allowing them both to map to ports 21 and 990 when needed.

**Comment by pc0124** [comment]
i tried the 0.0.0.0 and was finally able to run two compose files at the same time, but still getting error after requesting passive mode.

```
      - "4501:21"
      - "0.0.0.0:18700-18710:18700-18710"
      - "4991:990"
    networks:
      - bfrenftps-mntdatadevprojects-network

networks:
  bfrenftps-mntdatadevprojects-network:
    driver: bridge

Status:	Directory listing of "/" successful
```

```
      - "4502:21"
      - "0.0.0.0:10000-10010:18700-18710"
      - "4992:990"
    networks:
      - bfrenftps-mntdatadevdocker-network

networks:
  bfrenftps-mntdatadevdocker-network:
    driver: bridge

Response:	227 Entering Passive Mode (192,168,1,111,73,22).
Command:	LIST
Error:	The data connection could not be established: ECONNREFUSED - Connection refused by server
```

the second container works if i deliberately set the client to use active mode.
