### ISSUE TITLE
symlink a PEM file

### ISSUE THREAD

**Issue by ptzenos** [bfren/docker-ftps#55]
I'm trying to use a premade signed certificate but i can't find a way for it to work.

In the ssl folder on the host machine, I've created a symlink to the actual .pem file and renamed it to "server.pem".  The server doesn't pick up my certificate and a new self-signed .pem file is being created each time I recreate the container.

I've also tried modifying the env variable "FTPS_VSFTPD_CERT" in /overlay/etc/bf/init.d/10-env to point to my existing certificate with no luck. In that case, I can't start the container at all.

Is there anything else I could try?

Thanks

**Comment by bfren** [comment]
Symlinks don't work well with Docker - instead you need to do by mapping a volume.  If you're using Docker Compose you want something like this:

```yml
services:
  ftps:
    image: bfren/ftps:latest
    # service definition
    volumes:
      - /path/to/cert/cert.pem:/ssl/vsftpd.pem
```
